Restore an accidentally suppressed negation
Accidentally removed in 959e6fe49cfe1538f0b485b9b3691617613c4c52. This
caused `nix run` to systematically fail with

```
error: app program '/nix/store/…' is not in the Nix store
```