Revert "don't abort when given unmatched '}' with 'start-condition stack underflow'. This fixes  #751"
This reverts commit 8507b10be5decb4632661c8386467a40d69d0f77. It
breaks Nixpkgs:

$ nix-env -qa
error: syntax error, unexpected IND_STR, expecting '}', at /home/eelco/Dev/nixpkgs-stable/pkgs/top-level/python-packages.nix:7605:8